@file:Suppress("DEPRECATION")

package com.example.cpudefense

import android.app.Activity
import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Typeface
import android.view.GestureDetector
import android.view.MotionEvent
import android.view.SurfaceHolder
import android.view.SurfaceView
import androidx.core.content.res.ResourcesCompat
import androidx.core.view.GestureDetectorCompat
import com.example.cpudefense.GameMechanics.GamePhase
import com.example.cpudefense.GameMechanics.LevelMode
import com.example.cpudefense.utils.Logger
import com.example.cpudefense.effects.Background
import com.example.cpudefense.effects.Effects
import com.example.cpudefense.effects.Fader
import com.example.cpudefense.effects.Flipper
import com.example.cpudefense.effects.Mover
import com.example.cpudefense.gameElements.Chip
import com.example.cpudefense.networkmap.Coord
import com.example.cpudefense.networkmap.Network
import com.example.cpudefense.networkmap.Viewport
import kotlinx.coroutines.withContext
import java.util.concurrent.CopyOnWriteArrayList

@Suppress("RedundantOverride")
abstract class CommonView(context: Context):
    SurfaceView(context), SurfaceHolder.Callback,
    GestureDetector.OnGestureListener
{
    @Suppress("ConstPropertyName")
    companion object {
        // default sizes for graphical game elements.
        const val scoreTextSize = 36f
        const val scoreHeaderSize = 18f
        const val chipTextSize = 20f
        const val computerTextSize = 26f
        const val notificationTextSize = 22f
        const val instructionTextSize = 25f
        const val biographyTextSize = 20f
        const val heroCardNameSize = 18f
        const val heroCardTextSize = 14f
        const val purchaseButtonTextSize = 20f
        const val coinsAmountTextSize = 24f

        /** width for chip outlines as fraction of the chip's width */
        const val relativeOutlineWidth = 0.025f
        /** multiplier for the thickness of the border width for activated MEM and ACC */
        const val relativeOutlineWidthActivated = 5
        /** base width for lines between chips */
        const val connectorWidth = 6f
        /** base size of the little circles at the connectors' end */
        const val connectorRadius = 8f
        /** size of the cryptocoin icon on the score board */
        const val coinSizeOnScoreboard = 48
        /** base size of running cryptocoins */
        const val coinSizeOnScreen = 32
        /** base size of hero card in the marketplace */
        const val cardWidth = 220
        /** size of hero card in the marketplace */
        const val cardHeight = cardWidth * 1.41
        /** size of hero picture in the marketplace */
        const val cardPictureSize = cardWidth * 2 / 3
        /** horizontal size of LEDs, actual size can be smaller if there is too little space */
        const val preferredSizeOfLED = 20

        /** size of a chip in grid coordinates (scales with the viewport) */
        val chipSize = Coord(6,3)
        /** initial space in screen coordinates around the grid, with unshifted viewport */
        const val viewportMargin = 4
        const val minScoreBoardHeight = 100
        const val maxScoreBoardHeight = 320
        const val speedControlButtonSize = 48
        const val levelSnapshotIconSize = 120

        const val gridPointSize = 2
        const val gridBorderWidth = 2.0f
    }
    val theActivity = context as Activity
    abstract val gameMechanics: GameMechanics

    var canvas: Canvas? = null
    var effects: Effects? = null
    /** whether the viewport can be moved by scrolling or scaled by pinching */
    var scrollAllowed = true

    enum class ViewState { NORMAL, CHANGING_SIZE }
    /** state used to block movement when the user changes the viewport size */
    var viewState = ViewState.NORMAL
    /** lock used to synchronize drawing */
    var displayLock = Any()
    /** lock used to synchronize scrolling */
    var scrollLock = Any()

    val viewport = Viewport()
    var background = Background(this)
    private var backgroundColour = Color.BLACK
    val gestureDetector = GestureDetectorCompat(context, this)

    val cpuImage: Bitmap = BitmapFactory.decodeResource(resources, R.drawable.cpu)
    val hpBackgroundBitmap: Bitmap = BitmapFactory.decodeResource(resources, R.drawable.hp_key)
    val chipBitmap: Bitmap = BitmapFactory.decodeResource(resources, R.drawable.chip_surface)
    val chipAutogeneratedBitmap: Bitmap = BitmapFactory.decodeResource(resources, R.drawable.chip_autogenerated_surface)
    val zoomPlusIcon: Bitmap = BitmapFactory.decodeResource(resources, R.drawable.zoom_plus)
    val zoomMinusIcon: Bitmap = BitmapFactory.decodeResource(resources, R.drawable.zoom_minus)
    val coinIconBlue: Bitmap = BitmapFactory.decodeResource(resources, R.drawable.cryptocoin)
    val coinIconRed: Bitmap = BitmapFactory.decodeResource(resources, R.drawable.cryptocoin_red)
    val playIcon: Bitmap = BitmapFactory.decodeResource(resources, R.drawable.play_active)
    val pauseIcon: Bitmap = BitmapFactory.decodeResource(resources, R.drawable.pause_active)
    val fastIcon: Bitmap = BitmapFactory.decodeResource(resources, R.drawable.fast_active)
    val fastestIcon: Bitmap = BitmapFactory.decodeResource(resources, R.drawable.fastest_active)
    val returnIcon: Bitmap = BitmapFactory.decodeResource(resources, R.drawable.cancel_active)
    val moveLockIcon: Bitmap = BitmapFactory.decodeResource(resources, R.drawable.move_lock)
    val moveUnlockIcon: Bitmap = BitmapFactory.decodeResource(resources, R.drawable.move_unlock)

    /** font for displaying "computer messages" */
    lateinit var monoTypeface: Typeface
    lateinit var boldTypeface: Typeface

    /** text scale factor, based on ScaledDensity */
    var textScaleFactor = 1.0f
    /** general scale factor, based on Density */
    var scaleFactor = 1.0f
    /** space taken up by the top system bar */
    var topMargin = 0

    /** list of all mover objects that are created for game elements */
    var movers = CopyOnWriteArrayList<Mover>()
    /** list of all fader objects that are created for game elements */
    var faders = CopyOnWriteArrayList<Fader>()
    /** list of all flipper objects that are created for game elements */
    var flippers = CopyOnWriteArrayList<Flipper>()

    fun hasDefinedSize(): Boolean
    /** whether the game view and all its components know their size and can be used */
    {
        return (width > 0) && (height > 0)
    }

    /** called when the game view is created.
     * This is NOT the case when the user returns to the main menu
     *  and then continues the game.
     */
    open fun setupView()
    {
        this.visibility = VISIBLE
        this.holder.addCallback(this)
        backgroundColour = context.resources.getColor(R.color.network_background)
    }

    /** use Ubunto Mono font, if available. Otherwise use standard system monospace font */
    fun setComputerTypeface()
    {
        try
        {
            monoTypeface = ResourcesCompat.getFont(context, R.font.ubuntu_mono) ?: Typeface.MONOSPACE
            boldTypeface = ResourcesCompat.getFont(context, R.font.ubuntu_mono_bold) ?: Typeface.MONOSPACE
        }
        catch (_: Exception)
        {
            monoTypeface = Typeface.MONOSPACE
            boldTypeface = Typeface.MONOSPACE
        }
    }

    override fun surfaceCreated(p0: SurfaceHolder) {
    }

    override fun surfaceChanged(p0: SurfaceHolder, p1: Int, p2: Int, p3: Int) {
        // setSize(p2, p3)
    }

    override fun surfaceDestroyed(p0: SurfaceHolder) {
    }

    override fun onSizeChanged(w: Int, h: Int, oldw: Int, oldh: Int) {
        super.onSizeChanged(w, h, oldw, oldh)
        setComponentSize(w, h)
        background.setBackgroundDimensions(w, h, false)
    }

    @Suppress("UNUSED_VARIABLE", "unused")
    override fun onMeasure(widthMeasureSpec: Int, heightMeasureSpec: Int)
    /** function that is called to calculate height and width of this view. */
    {
        val widthMode = MeasureSpec.getMode(widthMeasureSpec)
        val widthSize = MeasureSpec.getSize(widthMeasureSpec)
        val heightMode = MeasureSpec.getMode(heightMeasureSpec)
        val heightSize = MeasureSpec.getSize(heightMeasureSpec)

        val width: Int = widthSize
        val height: Int = heightSize
        setMeasuredDimension(width, height)
    }

    open fun viewportHeight(h: Int): Int
    /** calculate viewport size for a given screen size
    @param h total height of screen
     */
    {
        return h
    }

    abstract fun settings(): Settings

    abstract fun logger(): Logger?

    abstract fun showReturnDialog()

    open fun setComponentSize(w: Int, h: Int)
    /** calculates and sets the size of the inner components of this view.
     * Also calculates the viewport dimensions.
     * Can be called multiple times. */
    {
        // adjust text sizes and scaling factor
        textScaleFactor = 0.70f * resources.displayMetrics.scaledDensity
        scaleFactor = 0.50f * resources.displayMetrics.density
    }

    override fun onTouchEvent(event: MotionEvent): Boolean {
        this.gestureDetector.onTouchEvent(event)
        // this.scaleGestureDetector.onTouchEvent(event)
        this.performClick()
        return true
    }

    override fun performClick(): Boolean {
        return super.performClick()
    }

    override fun onDown(motionEvent: MotionEvent): Boolean
    {
       return false
    }

    override fun onShowPress(p0: MotionEvent) {
    }

    override fun onSingleTapUp(p0: MotionEvent): Boolean {
        return false
    }

    override fun onScroll(p0: MotionEvent?, p1: MotionEvent, dx: Float, dy: Float): Boolean {
        return false
    }

    override fun onLongPress(motionEvent: MotionEvent)     {
    }

    override fun onFling(p0: MotionEvent?, p1: MotionEvent, p2: Float, p3: Float): Boolean {
        return false
    }

    /**  execute all movers and faders */
    open fun updateEffects()
    {
        for (m in movers)
        {
            if (m?.type == Mover.Type.NONE)
                movers.remove(m)
            else
                m?.update()
        }
        for (m in faders)
        {
            if (m?.type == Fader.Type.NONE)
                faders.remove(m)
            else
                m?.update()
        }
        for (m in flippers)
        {
            if (m?.type == Flipper.Type.NONE)
                flippers.remove(m)
            else
                m?.update()
        }
        if (showAdditionalEffects())
            effects?.snow?.updateGraphicalEffects()
    }

    open fun display()
    {
    }

    private fun showAdditionalEffects(): Boolean
    {
        if (gameMechanics.currentStageIdent.mode() == LevelMode.BASIC && gameMechanics.currentStageIdent.number == GameMechanics.specialLevelNumber)
            return (gameMechanics.state.phase == GamePhase.RUNNING || gameMechanics.state.phase == GamePhase.PAUSED)
        else
            return false
    }
    fun processClickOnNodes(network: Network, p0: MotionEvent): Boolean
    {
        // first, check if the click is inside one of the upgrade boxes of _any_ node
        for (obj in network.nodes.values) {
            val chip = obj as Chip
            for (upgrade in chip.upgradePossibilities)
                if (upgrade.onDown(p0)) {
                    chip.upgradePossibilities.clear()
                    return true
                }
            // if we come here, then the click was not on an update.
            if (chip.actualRect?.contains(p0.x.toInt(), p0.y.toInt()) == false)
                chip.upgradePossibilities.clear()  // clear update boxes of other chips
        }
        // check the nodes themselves
        for (obj in network.nodes.values)
            if (obj.onDown(p0))
                return true
        return false
    }


}